# Primary server config for static files
server {
    # Listen to port
    listen 80;
    
    # Server Name
    server_name local.gothic.com;
    
    # Logs
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    # Gzip
    gzip_static on;
    
    # Root
    root /var/www/gothic/public;

    # Add livereload.
    sub_filter '</head>' '<script src="http://localhost:35729/livereload.js"></script></head>';

    # Max file size.
    client_max_body_size 64M;

    # Main location
    location / {
        index index.php;
        try_files $uri $uri/ /index.php$is_args$args;
    }

    # Files expiration headers
    location ~* \.(?:ico|css|js|gif|jpe?g|png)$ {
        expires max;
        add_header Pragma public;
        add_header Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    # Run php files through fastcgi
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_pass gothic_php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}